on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add zeromq release-draft repo
      run: |
        echo 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-draft/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/network:messaging:zeromq:release-draft.list \
        && curl -fsSL https://download.opensuse.org/repositories/network:messaging:zeromq:release-draft/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/network_messaging_zeromq_release-draft.gpg > /dev/null

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libunwind-dev libzmq3-dev libmpv-dev libappindicator3-dev libcurl4-openssl-dev
        version: 1.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradle

    - name: Build native binaries
      run: ./gradlew nativeBinaries

    - name: Upload debug binary
      uses: actions/upload-artifact@v3
      with:
        name: spms_debug.kexe
        path: build/bin/native/debugExecutable/spmp-server.kexe

    - name: Upload release binary
      uses: actions/upload-artifact@v3
      with:
        name: spms_release.kexe
        path: build/bin/native/releaseExecutable/spmp-server.kexe
